<?php

namespace DDTrace\Integrations\Couchbase;

use DDTrace\Integrations\Integration;
use DDTrace\SpanData;
use DDTrace\Type;

class CouchbaseIntegration extends Integration
{
    const NAME = 'couchbase';

    /**
     * @return string The integration name.
     */
    public function getName()
    {
        return self::NAME;
    }

    /**
     * Add instrumentation to Couchbase requests
     */
    public function init()
    {
        \DDTrace\trace_method('Couchbase\Bucket', 'remove', function (SpanData $span, $args) use ($integration) {
            $this->addSpanDefaultMetadata(span, 'Bucket', 'remove');
            $span->meta['couchbase.remove'] = '';
        });

        \DDTrace\trace_method('Couchbase\Bucket', 'insert', function (SpanData $span, $args) use ($integration) {
            $this->addSpanDefaultMetadata(span, 'Bucket', 'insert');
            $span->meta['couchbase.insert'] = '';
        });

        \DDTrace\trace_method('Couchbase\Bucket', 'upsert', function (SpanData $span, $args) use ($integration) {
            $this->addSpanDefaultMetadata(span, 'Bucket', 'upsert');
            $span->meta['couchbase.upsert'] = '';
        });

        \DDTrace\trace_method('Couchbase\Bucket', 'replace', function (SpanData $span, $args) use ($integration) {
            $this->addSpanDefaultMetadata(span, 'Bucket', 'replace');
            $span->meta['couchbase.replace'] = '';
        });

        \DDTrace\trace_method('Couchbase\Bucket', 'get', function (SpanData $span, $args) use ($integration) {
            $this->addSpanDefaultMetadata(span, 'Bucket', 'get');
            $span->meta['couchbase.get'] = '';
        });

        \DDTrace\trace_method('Couchbase\Bucket', 'query', function (SpanData $span, $args) use ($integration) {
            $this->addSpanDefaultMetadata(span, 'Bucket', 'query');
            $span->meta['couchbase.query'] = '';
        });
    }

    /**
     * Add basic span metadata shared but all spans generated by the Couchbase integration.
     *
     * @param SpanData $span
     * @param string $class
     * @param string $method
     */
    public function addSpanDefaultMetadata(SpanData $span, $class, $method)
    {
        $span->name = "$class.$method";
        $span->service = CouchbaseIntegration::NAME;
        $span->resource = $method;
        $span->type = Type::COUCHBASE;
    }


}
