<?php

namespace DDTrace\Integrations\Couchbase;

use DDTrace\Integrations\Integration;
use DDTrace\SpanData;
use DDTrace\Type;

class CouchbaseIntegration extends Integration
{
    const NAME = 'couchbase';

    /**
     * @return string The integration name.
     */
    public function getName()
    {
        return self::NAME;
    }

    /**
     * Add instrumentation to Couchbase requests
     */
    public function init()
    {
        \DDTrace\trace_method('Couchbase\Bucket', 'get', function (SpanData $span, $args) use ($integration) {
            $span->meta['couchbase.get'] = '';
        });

        \DDTrace\trace_method('Couchbase\Bucket', 'query', function (SpanData $span, $args) use ($integration) {
            $span->meta['couchbase.get'] = '';
        });
    }

    /**
     * Add basic span metadata shared but all spans generated by the Couchbase integration.
     *
     * @param SpanData $span
     * @param string $class
     * @param string $method
     */
    public function addSpanDefaultMetadata(SpanData $span, $class, $method)
    {
        $span->name = $class . '.' . $method;
        $span->resource = $method;
        $span->type = Type::COUCHBASE;
        $span->service = CouchbaseIntegration::NAME;
    }


}
